# Generated by Django 5.2.6 on 2025-10-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0002_remove_parkingspot_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Card', 'Card'), ('Cash', 'Cash'), ('MobileMoney', 'MobileMoney')], default='Card', max_length=50),
        ),
    ]
